trigger:
- master

pool:
  "default"

variables:
  - name: CloudInitContent


steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(48795d1d-efc3-44f3-a40e-3565ec977a1a)'
    subscriptionId: '48795d1d-efc3-44f3-a40e-3565ec977a1a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RG2'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\KeyVault\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\KeyVault\azuredeploy.parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(48795d1d-efc3-44f3-a40e-3565ec977a1a)'
    subscriptionId: '48795d1d-efc3-44f3-a40e-3565ec977a1a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RG2'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\KeyVault\addSecretTemplate.json'
    overrideParameters: '-vaultName $(KeyVaultName) -secretValue $(AdminPass)'
    deploymentMode: 'Incremental'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $CloudContent = Get-Content -Path .\AzureResourceGroup1\cloud-init.txt -RAW
      $EncodedContent = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($CloudContent))
      Write-Host $encodedContent
      Write-Host "##vso[task.setvariable variable=CloudInitContent;]$encodedContent"

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(48795d1d-efc3-44f3-a40e-3565ec977a1a)'
    subscriptionId: '48795d1d-efc3-44f3-a40e-3565ec977a1a'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RG1'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\AzureResourceGroup1\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\AzureResourceGroup1\azuredeploy.parameters.json'
    overrideParameters: '-customData $(CloudInitContent) -adminPassword $(AdminPass)'
    deploymentMode: 'Incremental'
